"""Add category and unit_price to Stock

Revision ID: 0af841d70a66
Revises: c3c5a4e65e77
Create Date: 2025-09-28 17:15:48.776111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af841d70a66'
down_revision = 'c3c5a4e65e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('unit_price')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
